In [1]:
!pip install pyspark

Collecting pyspark
  Downloading pyspark-3.5.2.tar.gz (317.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.3/317.3 MB 829.5 kB/s eta 0:00:0000:0100:11
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /opt/conda/lib/python3.10/site-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.2-py2.py3-none-any.whl size=317812364 sha256=bb0319020883a91b13ebdd98678465c95eba4b528b7f9c8bf461ca4ef4e9e77a
  Stored in directory: /root/.cache/pip/wheels/34/34/bd/03944534c44b677cd5859f248090daa9fb27b3c8f8e5f49574
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.5.2

In [11]:
from pyspark.sql import SparkSession

In [12]:
spark = SparkSession.builder.appName("PySparkExample").getOrCreate()

In [13]:
data = [("Alice", 25), ("Bob", 30), ("Charlie", 35)]
#Create a DataFrame
data = [("Alice", 25), ("Bob", 30), ("Charlie", 35)]
df = spark.createDataFrame(data, ["Name", "Age"])

In [14]:
df.show()

+-------+---+
|   Name|Age|
+-------+---+
|  Alice| 25|
|    Bob| 30|
|Charlie| 35|
+-------+---+

In [15]:
df_filtered = df.filter(df["Age"] > 30)
df_filtered.show()

+-------+---+
|   Name|Age|
+-------+---+
|Charlie| 35|
+-------+---+

In [16]:
df.select("Name", "Age").show()

+-------+---+
|   Name|Age|
+-------+---+
|  Alice| 25|
|    Bob| 30|
|Charlie| 35|
+-------+---+

In [18]:
from pyspark.sql import functions as F

# Add a new column "Gender" with the value "Female" for all rows
df_with_gender = df.withColumn("Gender", F.lit("Female"))

# Show the result
df_with_gender.show()

+-------+---+------+
|   Name|Age|Gender|
+-------+---+------+
|  Alice| 25|Female|
|    Bob| 30|Female|
|Charlie| 35|Female|
+-------+---+------+

In [19]:
# Filtering rows based on a condition
df_filtered = df.filter(df["Age"] > 30)
df_filtered.show()

+-------+---+
|   Name|Age|
+-------+---+
|Charlie| 35|
+-------+---+

In [21]:
# Sorting the DataFrame
df_sorted = df.orderBy(df["Age"])
df_sorted.show()

+-------+---+
|   Name|Age|
+-------+---+
|  Alice| 25|
|    Bob| 30|
|Charlie| 35|
+-------+---+

In [24]:
from pyspark.sql import functions as F

# Grouping by 'Gender' and calculating the average 'Age'
df_grouped = df_with_gender.groupBy("Gender").agg(F.avg("Age").alias("Average_Age"))

# Show the result
df_grouped.show()

+------+-----------+
|Gender|Average_Age|
+------+-----------+
|Female|       30.0|
+------+-----------+